default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: "1234567"
  host: localhost
  pool: 5

development:
  <<: *default
  database: GoAbackend_dev

test:
  <<: *default
  database: GoAbackend_test
